export const ALL_ADMIN_DATALIST_SUCCESS = 'ALL_ADMIN_DATALIST_SUCCESS';
export const ALL_ADMIN_RISKLIST_SUCCESS = 'ALL_ADMIN_RISKLIST_SUCCESS';
export const ALL_ADMIN_ORGUNIT_LIST_SUCCESS = 'ALL_ADMIN_ORGUNIT_LIST_SUCCESS';
export const ADMIN_RISK_MERGE_REQUEST_SUCCESS = 'ADMIN_RISK_MERGE_REQUEST_SUCCESS';
