export const ALL_DETECTION_LIST_SUCCESS = 'ALL_DETECTION_LIST_SUCCESS';
export const ALL_SB_DETECTION_RULES_STATUS_SUCCESS = 'ALL_SB_DETECTION_RULES_STATUS_SUCCESS';
export const ALL_SB_DETECTION_SCENARIOS_STATUS_SUCCESS = 'ALL_SB_DETECTION_SCENARIOS_STATUS_SUCCESS';
export const ALL_SB_DETECTION_PROFILES_STATUS_SUCCESS = 'ALL_SB_DETECTION_PROFILES_STATUS_SUCCESS';
export const DETECTION_ID_SELECTED_SB = 'DETECTION_ID_SELECTED_SB';
export const DETECTION_NAME_SELECTED_SB = 'DETECTION_NAME_SELECTED_SB';
