/*
export let GET_LOGIN_INIT_CACHE = 'GET_LOGIN_INIT_CACHE';
export let AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export let SHOW_LOGIN_ERR_MSG = 'SHOW_LOGIN_ERR_MSG';
export let LOGOUT_USER = 'LOGOUT_USER';
export let ALL_ALERT_USER_PREFERENCE = 'ALL_ALERT_USER_PREFERENCE';*/

export enum actionType {
    GET_LOGIN_INIT_CACHE = 'GET_LOGIN_INIT_CACHE',
    AUTHENTICATE_USER = 'AUTHENTICATE_USER',
    SHOW_LOGIN_ERR_MSG = 'SHOW_LOGIN_ERR_MSG',
    LOGOUT_USER = 'LOGOUT_USER',
}

export default actionType;
