export const GET_LOGIN_INIT_CACHE = 'GET_LOGIN_INIT_CACHE';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SHOW_LOGIN_ERR_MSG = 'SHOW_LOGIN_ERR_MSG';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ALL_ALERT_USER_PREFERENCE = 'ALL_ALERT_USER_PREFERENCE';
export const MANAGE_DEFAULT_DISPLAY = 'MANAGE_DEFAULT_DISPLAY';
